---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Set fluentd_version for Ubuntu 20.04.
      set_fact:
        fluentd_version: 4
      when: ansible_distribution_version == '20.04'

  roles:
    - role: geerlingguy.fluentd
